version: '3.4'

services:
  rentcommandapi:
    image: ${DOCKER_REGISTRY-}rentcommandapi
    build:
      context: .
      dockerfile: RentCommand/Dockerfile
    depends_on: 
        - mongo
        - kafka

  mongo:
    container_name: mongo
    image: mongo:latest

  zookeeper:
    container_name: zookeeper
    image: bitnami/zookeeper

  kafka:
    container_name: kafka
    image: bitnami/kafka
    depends_on:
      - zookeeper